plugin:
  groupName: mybatisPlusLombok
  name: serviceInterface
  description: serviceInterface生成插件
  generator: com.qxs.plugin.generator.mybatis.plus.lombok.service.MybatisPlusLombokServiceGenerator
  templatePath: template.ftl
  fileRelativeDir: mybatisPlusLombok/service
  fileSuffix: .java
  prefix: I
  suffix: Service
  dependencies: entity #依赖的插件,以英文逗号(,)分割