plugin:
  groupName: mybatis
  name: mapper
  description: mapper生成插件
  generator: com.qxs.plugin.generator.mybatis.mapper.MybatisMapperGenerator
  templatePath: template.ftl
  fileRelativeDir: mybatis/mapper
  fileSuffix: .xml
  prefix:
  suffix: -mapper
  dependencies: entity,dao #依赖的插件,以英文逗号(,)分割