plugin:
  groupName: jpaLombok
  name: businessController
  description: businessController生成插件
  generator: com.qxs.plugin.generator.jpa.lombok.business.controller.JpaLombokBusinessControllerGenerator
  templatePath: template.ftl
  fileRelativeDir: jpaLombok/businessController
  fileSuffix: .java
  prefix:
  suffix: Controller
  dependencies: entity,business #依赖的插件,以英文逗号(,)分割