plugin:
  groupName: jpaLombok
  name: business
  description: business生成插件
  generator: com.qxs.plugin.generator.jpa.lombok.business.JpaLombokBusinessGenerator
  templatePath: template.ftl
  fileRelativeDir: jpaLombok/business
  fileSuffix: .java
  prefix:
  suffix: Business
  dependencies: entity,serviceInterface #依赖的插件,以英文逗号(,)分割