plugin:
  groupName: mybatisPlusLombok
  name: businessController
  description: businessController生成插件
  generator: com.qxs.plugin.generator.mybatis.plus.lombok.business.controller.MybatisPlusLombokBusinessControllerGenerator
  templatePath: template.ftl
  fileRelativeDir: mybatisPlusLombok/businessController
  fileSuffix: .java
  prefix:
  suffix: Controller
  dependencies: entity,business #依赖的插件,以英文逗号(,)分割