plugin:
  groupName: mybatis
  name: dao
  description: dao生成插件
  generator: com.qxs.plugin.generator.mybatis.dao.MybatisDAOGenerator
  templatePath: template.ftl
  fileRelativeDir: mybatis/dao
  fileSuffix: .java
  prefix: I
  suffix: DAO
  dependencies: entity #依赖的插件,以英文逗号(,)分割