plugin:
  groupName: mybatisPlusLombok
  name: business
  description: business生成插件
  generator: com.qxs.plugin.generator.mybatis.plus.lombok.business.MybatisPlusLombokBusinessGenerator
  templatePath: template.ftl
  fileRelativeDir: mybatisPlusLombok/business
  fileSuffix: .java
  prefix:
  suffix: Business
  dependencies: entity,serviceInterface #依赖的插件,以英文逗号(,)分割