plugin:
  groupName: mybatisLombok
  name: serviceImpl
  description: serviceImpl生成插件
  generator: com.qxs.plugin.generator.mybatis.lombok.service.impl.MybatisLombokServiceImplGenerator
  templatePath: template.ftl
  fileRelativeDir: mybatisLombok/service/impl
  fileSuffix: .java
  prefix:
  suffix: ServiceImpl
  dependencies: entity,dao,serviceInterface #依赖的插件,以英文逗号(,)分割