plugin:
  groupName: mybatisLombok
  name: entity
  description: 实体类生成插件
  templatePath: template.ftl
  generator: com.qxs.plugin.generator.mybatis.lombok.entity.MybatisLombokEntityGenerator
  fileRelativeDir: mybatisLombok/entity
  fileSuffix: .java
  prefix:
  suffix:
  dependencies:  #依赖的插件,以英文逗号(,)分割