plugin:
  groupName: mybatisLombok
  name: controller
  description: controller生成插件
  generator: com.qxs.plugin.generator.mybatis.lombok.service.controller.MybatisLombokControllerGenerator
  templatePath: template.ftl
  fileRelativeDir: mybatisLombok/controller
  fileSuffix: .java
  prefix:
  suffix: Controller
  dependencies: entity,serviceInterface #依赖的插件,以英文逗号(,)分割