plugin:
  groupName: jpaLombok
  name: controller
  description: controller生成插件
  generator: com.qxs.plugin.generator.jpa.lombok.service.controller.JpaLombokControllerGenerator
  templatePath: template.ftl
  fileRelativeDir: jpaLombok/controller
  fileSuffix: .java
  prefix:
  suffix: Controller
  dependencies: entity,serviceInterface #依赖的插件,以英文逗号(,)分割