plugin:
  groupName: mybatis
  name: business
  description: business生成插件
  generator: com.qxs.plugin.generator.mybatis.business.MybatisBusinessGenerator
  templatePath: template.ftl
  fileRelativeDir: mybatis/business
  fileSuffix: .java
  prefix:
  suffix: Business
  dependencies: entity,serviceInterface #依赖的插件,以英文逗号(,)分割