plugin:
  groupName: mybatisPlus
  name: controller
  description: controller生成插件
  generator: com.qxs.plugin.generator.mybatis.plus.service.controller.MybatisPlusControllerGenerator
  templatePath: template.ftl
  fileRelativeDir: mybatisPlus/controller
  fileSuffix: .java
  prefix:
  suffix: Controller
  dependencies: entity,serviceInterface #依赖的插件,以英文逗号(,)分割