plugin:
  groupName: mybatisLombok
  name: business
  description: business生成插件
  generator: com.qxs.plugin.generator.mybatis.lombok.business.MybatisLombokBusinessGenerator
  templatePath: template.ftl
  fileRelativeDir: mybatisLombok/business
  fileSuffix: .java
  prefix:
  suffix: Business
  dependencies: entity,serviceInterface #依赖的插件,以英文逗号(,)分割