plugin:
  groupName: jpa
  name: serviceInterface
  description: serviceInterface生成插件
  generator: com.qxs.plugin.generator.jpa.service.JpaServiceGenerator
  templatePath: template.ftl
  fileRelativeDir: jpa/service
  fileSuffix: .java
  prefix: I
  suffix: Service
  dependencies: entity #依赖的插件,以英文逗号(,)分割