plugin:
  groupName: mybatis
  name: controller
  description: controller生成插件
  generator: com.qxs.plugin.generator.mybatis.service.controller.MybatisControllerGenerator
  templatePath: template.ftl
  fileRelativeDir: mybatis/controller
  fileSuffix: .java
  prefix:
  suffix: Controller
  dependencies: entity,serviceInterface #依赖的插件,以英文逗号(,)分割