plugin:
  groupName: mybatis
  name: businessController
  description: businessController生成插件
  generator: com.qxs.plugin.generator.mybatis.business.controller.MybatisBusinessControllerGenerator
  templatePath: template.ftl
  fileRelativeDir: mybatis/businessController
  fileSuffix: .java
  prefix:
  suffix: Controller
  dependencies: entity,business #依赖的插件,以英文逗号(,)分割