plugin:
  groupName: mybatisLombok
  name: businessController
  description: businessController生成插件
  generator: com.qxs.plugin.generator.mybatis.lombok.business.controller.MybatisLombokBusinessControllerGenerator
  templatePath: template.ftl
  fileRelativeDir: mybatisLombok/businessController
  fileSuffix: .java
  prefix:
  suffix: Controller
  dependencies: entity,business #依赖的插件,以英文逗号(,)分割