plugin:
  groupName: mybatisLombok
  name: mapper
  description: mapper生成插件
  generator: com.qxs.plugin.generator.mybatis.lombok.mapper.MybatisLombokMapperGenerator
  templatePath: template.ftl
  fileRelativeDir: mybatisLombok/mapper
  fileSuffix: .xml
  prefix:
  suffix: -mapper
  dependencies: entity,dao #依赖的插件,以英文逗号(,)分割