plugin:
  groupName: jpa
  name: businessController
  description: businessController生成插件
  generator: com.qxs.plugin.generator.jpa.business.controller.JpaBusinessControllerGenerator
  templatePath: template.ftl
  fileRelativeDir: jpa/businessController
  fileSuffix: .java
  prefix:
  suffix: Controller
  dependencies: entity,business #依赖的插件,以英文逗号(,)分割